apiVersion: v1beta3
baseDomain: "{{ settings.baseDomain }}"
compute:
- name: worker
  platform: {}
  replicas: {{ settings.numWorkers }}
controlPlane:
  name: master
  platform: {}
  replicas: {{ settings.numMasters }}
metadata:
  creationTimestamp: null
  name: "{{ settings.clusterName }}"
networking:
  clusterNetworks:
  - cidr: "{{ settings.clusterCIDR }}"
    hostSubnetLength: {{ settings.clusterSubnetLength }}
  machineCIDR: "{{ settings.machineCIDR }}"
  serviceCIDR: "{{ settings.serviceCIDR }}"
  type: "{{ settings.SDNType }}"
platform:
  aws:
    region: "{{ settings.AWSRegion }}"
pullSecret: '{{ settings.pullSecret }}'
sshKey: |
  {{ settings.SSHKey }}
