---
- name: install epel repo
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present
  when: ansible_distribution == 'CentOS'

- name: install all required packages
  yum:
    name: "{{ netlab_packages }}"
    state: present
  when: inventory_hostname != 'localhost'
  ignore_errors: yes

- name: start required services
  service:
    name: libvirtd
    state: started

- name: setup base directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ netlab_virt_base_path }}"
    - "{{ netlab_virt_vm_path }}"
    - "{{ netlab_virt_images_path }}"
    - "{{ netlab_virt_iso_path }}"

- name: Creates NFS directory
  file: path=/var/nfs state=directory

- name: Create NGINX directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/etc/nginx"
    - "/srv/nginx/images"

- name: NGINX container
  docker_container:
    name: nginx
    image: nginx
    state: started
    ports:
    - "80:80"
    volumes:
    - "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    - "/srv/nginx:/usr/share/nginx/html:ro"

- name: Download Golang 1.10
  get_url:
    url: https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz
    dest: /root/go.tar.gz
    mode: 0755

- name: Extract tarball
  unarchive:
    src: /root/go.tar.gz
    dest: /root/

- name: Add k8S repository
  yum_repository:
    name: kubernetes
    description: Kubernetes YUM repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    state: present

- name: Add entry in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^192'
    line: '192.168.126.3 testcluster-api.edge.testing'

- name: Add NFS server exports
  lineinfile:
    path: /etc/exports
    line: '/var/nfs *(rw,no_root_squash,sync)'

- name: Enable/start NFS services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: True
  with_items:
    - "nfs-server"
    - "nfs-lock"
    - "nfs-idmap"

- name: NFS firewall rules
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - "nfs"
    - "mountd"

- name: NFS firewall zone state
  firewalld:
    zone: public
    state: present
    permanent: true

- name: Enable/start TFTP services
  systemd:
    name: "tftp"
    state: started
    enabled: True

- name: TFP firewall rules
  firewalld:
    zone: public
    service: "tftp"
    permanent: true
    state: enabled

- name: Create tftp folder if not exists
  file:
      path: /var/lib/tftpboot
      state: directory
      mode: 0775

- name: Create content inside tftpboot folder
  file:
      src: /usr/share/syslinux/pxelinux.0
      dest: /var/lib/tftpboot/pxelinux.0
      state: link

- name: Generate bootstrap ipxe file
  template:
    src: templates/bootstrap.ipxe.j2
    dest: /var/lib/tftpboot/bootstrap.ipxe
    mode: 0644

- name: Configure selinux policy for NGINX
  sefcontext:
    target: '/srv/nginx/images'
    setype: httpd_sys_content_t
    state: present
