---
- name: Perform qcow2 image building
  hosts: provision_host
  gather_facts: yes
  tasks:
    - name: Remove the directory to force it to be empty
      file:
        path: /tmp/cosa_build
        state: absent

    - name: Create target directories
      file:
          path: /tmp/cosa_build
          state: directory
          mode: 0775

    - name: Update certificates
      shell: |
        curl -kL -o /etc/pki/ca-trust/source/anchors/Red_Hat_IT_Root_CA.crt https://password.corp.redhat.com/RH-IT-Root-CA.crt
        update-ca-trust
      become: true

    - name: Copy file with coreos-assembler instructions
      copy:
          src: templates/cosa_build_rhcos_image.sh.j2
          dest: /tmp/cosa_build/cosa_build_rhcos_image.sh
          mode: 0755

    - name: Install coreos-assembler and build images
      shell: |
          pushd /tmp/cosa_build
          #alias coreos-assembler="podman run --rm --net=host -ti --privileged --userns=host -v /tmp/cosa_build:/srv --workdir /srv docker-registry.upshift.redhat.com/redhat-coreos/coreos-assembler:stage"
          alias coreos-assembler="podman run --rm --net=host -ti --privileged --userns=host -v /tmp/cosa_build:/srv --workdir /srv quay.io/coreos-assembler/coreos-assembler:latest"
          coreos-assembler shell /srv/cosa_build_rhcos_image.sh
          popd

    - name: Extract image to workspace
      fetch:
          src: /tmp/cosa_build/builds/latest/redhat-coreos-maipo-47-qemu.qcow2
          dest: "{{ lookup('env', 'WORKSPACE') }}/rhcos-qemu.qcow2"
          flat: yes

    - name: Execute qcow2 to raw conversion
      shell: |
        qemu-img convert {{ lookup('env', 'WORKSPACE') }}/rhcos-qemu.qcow2 {{ lookup('env', 'WORKSPACE') }}/rhcos-qemu.raw

    - name: Extract iso to workspace
      fetch:
          src: /tmp/cosa_build/builds/latest/redhat-coreos-maipo-47.iso
          dest: "{{ lookup('env', 'WORKSPACE') }}/rhcos.iso"
          flat: yes

    - name: Extract iso and copy files
      shell: |
          TEMP_DIRECTORY=$(mktemp -d)
          mount -o loop {{ lookup('env', 'WORKSPACE') }}/rhcos.iso ${TEMP_DIRECTORY}
          cp ${TEMP_DIRECTORY}/vmlinuz {{ lookup('env', 'WORKSPACE') }}/vmlinuz
          cp ${TEMP_DIRECTORY}/initramfs.img {{ lookup('env', 'WORKSPACE') }}/initrd.img
          chmod a+r {{ lookup('env', 'WORKSPACE') }}/initrd.img



