---
- name: provision the cloud virtual machine host
  hosts: provision_host
  gather_facts: yes
  tags: provision_host

  tasks:
    - name: install dependencies
      yum:
        name:
          - python-pip
          - python-devel
        state: latest

- name: Generate fact for pubkey path
  hosts: provision_host
  gather_facts: yes
  tags: provision_host
  tasks:
    - name: Register fact for pubkey path
      set_fact:
        pubkey_path: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"

- name: generate ignition file with pubkey
  hosts: provision_host
  gather_facts: yes
  tags: provision_host
  vars:
    core_pubkey: "{{ lookup('file', pubkey_path) }}"
  tasks:
    - name: Generate ignition file with pubkey
      template:
        src: templates/ssh_key.ign.j2
        dest: "{{ lookup('env', 'IGNITION_PATH') }}/ssh_key.ign"
        mode: 0644

- name: provision the virtual machines
  hosts: hosts
  gather_facts: no
  become: yes
  tags: provision_vms

  tasks:
    - name: build and start the network virtual machines
      import_role:
        name: netlab
        tasks_from: build
      vars:
        netlab_nodes_path: "{{ playbook_dir }}/../nodes_image_build"
        netlab_files_path: "{{ playbook_dir }}/../files"

    - name: Retrieve IP of generated VM
      shell: |
        for mac in `virsh domiflist server01 |grep -o -E "([0-9a-f]{2}:){5}([0-9a-f]{2})"` ; do
            arp -e |grep $mac  |grep -o -P "^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"
        done
      register: vm_ip

    - name: Add new host to inventory
      add_host:
          name: "{{ vm_ip.stdout }}"
          groups: build_host
          ansible_user: core

    - name: Wait for VM to be available
      wait_for:
          port: 22
          host: "{{ vm_ip.stdout }}"
          delay: 10

- name: Install dependencies to build VM
  hosts: build_host
  gather_facts: yes
  become: yes
  tags: build_image

  tasks:
    - name: disable selinux
      selinux:
          policy: targeted
          state: permissive

    - name: Enable /usr modification
      shell: rpm-ostree usroverlay
      ignore_errors: true

    - name: Clone coreos-dracut project
      shell: |
          podman run -ti --rm -v {{ lookup('env', 'HOME') }}:/root -v /tmp:/git alpine/git clone https://github.com/yrobla/coreos-dracut.git
      ignore_errors: true

    - name: Create needed directories
      file:
          path: "{{ item }}"
          state: directory
          mode: 0755
      with_items:
          - /tmp/isolinux
          - /tmp/genisoimage
          - /usr/lib/dracut/modules.d/90coreos
          - /usr/share/syslinux

    - name: Copy module to dracut
      shell: |
          cp -R /tmp/coreos-dracut/dracut-module/* /usr/lib/dracut/modules.d/90coreos/

    - name: Install syslinux
      shell: |
          podman run -v /tmp/isolinux:/usr/share/syslinux/ -d --name isolinux fedora:latest /bin/bash -c "dnf -y install /usr/share/syslinux/isolinux.bin;sleep 300"
      ignore_errors: true

    - name: Install genisoimage
      shell: |
          podman run -v /tmp/genisoimage:/tmp/ -d --name genisoimage fedora:latest /bin/bash -c "dnf -y install genisoimage;cp /usr/bin/mkisofs /tmp/ ; sleep 300"
      ignore_errors: true

    - name: Wait until genisoimage file is populated
      wait_for:
          path: /tmp/genisoimage/mkisofs

    - name: And copy to the right path
      shell: |
          cp /tmp/genisoimage/mkisofs /usr/bin/

    - name: Wait until isolinux is populated
      wait_for:
          path: /tmp/isolinux/isolinux.bin

    - name: And copy to the right path
      shell: |
          cp -R /tmp/isolinux/* /usr/share/syslinux

    - name: Find vmlinuz file
      shell: |
          find /boot -name vmlinuz*x86_64
      register: vmlinuz_file

    - name: And copy to boot directory
      shell: |
          cp {{ vmlinuz_file }} /boot/

    - name: Download extra libraries
      get_url:
          url: https://rpmfind.net/linux/fedora/linux/releases/27/Everything/x86_64/os/Packages/l/libusal-1.1.11-37.fc27.x86_64.rpm
          dest: /tmp/libusal.rpm
          mode: 0644

    - name: Extract extra libraries
      shell: |
          rpm2cpio /tmp/libusal.rpm | cpio -idmv

    - name: Copy libraries to the right path
      shell: |
          cp /tmp/usr/lib64/libusal.so.0 /usr/lib64/
          cp /tmp/usr/lib64/librols.so.0* /usr/lib64/

    - name: Execute build
      shell: |
          cd /tmp/coreos-dracut/build
          make clean && make x86_64

