---
- name: provision the cloud virtual machine host
  hosts: provision_host
  gather_facts: yes
  tags: provision_host

  tasks:
    - name: install dependencies
      yum:
        name:
          - python-pip
          - python-devel
        state: latest

- name: Generate fact for pubkey path
  hosts: provision_host
  gather_facts: yes
  tags: provision_host
  tasks:
    - name: Register fact for pubkey path
      set_fact:
        pubkey_path: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"

- name: generate ignition file with pubkey
  hosts: provision_host
  gather_facts: yes
  tags: provision_host
  vars:
    core_pubkey: "{{ lookup('file', pubkey_path) }}"
  tasks:
    - name: Generate ignition file with pubkey
      template:
        src: templates/ssh_key.ign.j2
        dest: "{{ lookup('env', 'IGNITION_PATH') }}/ssh_key.ign"
        mode: 0644

- name: provision the virtual machines
  hosts: hosts
  gather_facts: no
  become: yes
  tags: provision_vms

  tasks:
    - name: build and start the network virtual machines
      import_role:
        name: netlab
        tasks_from: build
      vars:
        netlab_nodes_path: "{{ playbook_dir }}/../nodes_image_build"
        netlab_files_path: "{{ playbook_dir }}/../files"
