---
- name: Generate fact for pubkey path
  hosts: provision_host
  gather_facts: yes
  tasks:
    - name: Create target directories
      file:
          path: "{{ item }}"
          state: directory
          mode: 0775
      with_items:
          - /tmp/cosa_build

    - name: Update certificates
      shell: |
        sudo curl -kL -o /etc/pki/ca-trust/source/anchors/Red_Hat_IT_Root_CA.crt https://password.corp.redhat.com/RH-IT-Root-CA.crt
        sudo update-ca-trust

    - name: Copy file with coreos-assembler instructions
      copy:
          src: templates/cosa_build_rhcos_image.sh.j2
          dest: /tmp/cosa_build/cosa_build_rhcos_image.sh
          mode: 0755

    - name: Install coreos-assembler and build images
      shell: |
          alias coreos-assembler="podman run --rm --net=host -ti --privileged --userns=host -v /tmp/cosa_build:/srv --workdir /srv docker-registry.upshift.redhat.com/redhat-coreos/coreos-assembler:stage"
          coreos-assembler shell /srv/cosa_build_rhcos_image.sh

    - name: Extract image to workspace
      fetch:
          src: /tmp/cosa_build/builds/latest/redhat-coreos-maipo-47-qemu.qcow2
          dest: "{{ lookup('env', 'WORKSPACE') }}/rhcos-qemu.qcow2"
          flat: yes

    - name: Execute qcow2 to raw conversion
      shell: |
        qemu-img convert {{ lookup('env', 'WORKSPACE') }}/rhcos-qemu.qcow2 {{ lookup('env', 'WORKSPACE') }}/rhcos-qemu.raw

