---
- name: provision the cloud virtual machine host
  hosts: provision_host
  gather_facts: yes
  tags: provision_host

  tasks:
    - name: install dependencies
      yum:
        name:
          - python-pip
          - python-devel
        state: latest

- name: Generate fact for pubkey path
  hosts: provision_host
  gather_facts: yes
  tags: provision_host
  tasks:
    - name: Register fact for pubkey path
      set_fact:
        pubkey_path: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"

- name: generate ignition file with pubkey
  hosts: provision_host
  gather_facts: yes
  tags: provision_host
  vars:
    core_pubkey: "{{ lookup('file', pubkey_path) }}"
  tasks:
    - name: Generate ignition file with pubkey
      template:
        src: templates/ssh_key.ign.j2
        dest: "{{ lookup('env', 'IGNITION_PATH') }}/ssh_key.ign"
        mode: 0644

- name: provision the virtual machines
  hosts: hosts
  gather_facts: no
  become: yes
  tags: provision_vms

  tasks:
    - name: build and start the network virtual machines
      import_role:
        name: netlab
        tasks_from: build
      vars:
        netlab_nodes_path: "{{ playbook_dir }}/../nodes_image_build"
        netlab_files_path: "{{ playbook_dir }}/../files"

    - name: Retrieve IP of generated VM
      shell: |
        for mac in `virsh domiflist server01 |grep -o -E "([0-9a-f]{2}:){5}([0-9a-f]{2})"` ; do
            arp -e |grep $mac  |grep -o -P "^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"
        done
      register: vm_ip

    - name: Add new host to inventory
      add_host:
          name: "{{ vm_ip.stdout }}"
          groups: build_host

- name: Install dependencies to build VM
  hosts: build_host
  gather_facts: yes
  become: yes
  tags: build_image

  tasks:
    - name: disable selinux
      selinux:
          policy: targeted
          state: permissive

    - name: Clone coreos-dracut project
      shell: |
          podman run -ti --rm -v {{ lookup('env', 'HOME') }}:/root -v /tmp:/git alpine/git clone https://github.com/yrobla/coreos-dracut.git

    - name: Install syslinux
      shell: |
          podman run -v /tmp/isolinux:/usr/share/syslinux/ -d --name isolinux fedora:latest /bin/bash -c "dnf -y install /usr/share/syslinux/isolinux.bin;sleep 300"

    - name: Install genisoimage
      shell: |
          podman run -v /tmp/genisoimage:/tmp/ -d --name genisoimage fedora:latest /bin/bash -c "dnf -y install genisoimage;cp /usr/bin/mkisofs /tmp/ ; sleep 300"
